# Generated by Django 3.1.2 on 2020-10-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
