# Generated by Django 3.1.2 on 2020-10-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComm', '0002_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='topc_title',
            new_name='topc',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topc_title',
            new_name='title',
        ),
    ]
