# Generated by Django 3.1.2 on 2020-10-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComm', '0003_auto_20201011_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='userComment',
            new_name='user',
        ),
    ]
