# Generated by Django 3.1.2 on 2020-10-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComm', '0004_auto_20201011_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply',
        ),
    ]
