# Generated by Django 3.1.2 on 2020-10-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicComm', '0005_remove_comments_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='topc',
            new_name='topic',
        ),
    ]
